# -*- coding: utf-8 -*-
"""web scraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B4d5IuQ7IL_OBiS_VhADC8-n2GyYYFdl

Task 1
#Python Web Scraping
#This task tests your understanding of Python language in applying it to a specific well-defined task of web scraping.
"""

import os
import requests
import re
from bs4 import BeautifulSoup  # Import BeautifulSoup library

# Global variable for URL
url = None

# Function to get the HTML source text of the Medium article
def get_page():
    global url

    # Ask the user to input the URL of a Medium article
    url = input("Enter URL of a Medium article: ")

    # Handling possible error
    if not re.match(r'https?://medium.com/', url):
        print('Please enter a valid Medium article URL.')
        sys.exit(1)

    # Call get method in requests object, pass URL and collect it in res
    try:
        res = requests.get(url)
    except requests.RequestException as e:
        print(f"Request failed: {e}")
        sys.exit(1)

    res.raise_for_status()
    soup = BeautifulSoup(res.text, 'html.parser')
    return soup

# Function to remove all the HTML tags and replace some with specific strings
def clean(text):
    rep = {"<br>": "\n", "<br/>": "\n", "<li>": "\n"}
    rep = dict((re.escape(k), v) for k, v in rep.items())
    pattern = re.compile("|".join(rep.keys()))
    text = pattern.sub(lambda m: rep[re.escape(m.group(0))], text)
    text = re.sub('\<(.*?)\>', '', text)
    return text

def collect_text(soup):
    text = f'URL: {url}\n\n'
    para_text = soup.find_all('p')
    print(f"Paragraphs text = \n {para_text}")
    for para in para_text:
        text += f"{para.text}\n\n"
    return text

# Function to save file in the current directory
def save_file(text):
    if not os.path.exists('./scraped_articles'):
        os.mkdir('./scraped_articles')
    name = url.split("/")[-1]
    fname = f'scraped_articles/{name}.txt'

    # Write a file using with (2 lines)
    with open(fname, 'w', encoding='utf-8') as file:
        file.write(text)

    print(f'File saved in directory {fname}')

if __name__ == '__main__':
    text = collect_text(get_page())
    save_file(text)
    # Instructions to Run this Python code
    # Provide URL as https://medium.com/@subashgandyer/papa-what-is-a-neural-network-c5e5cc427c7